language: node_js
env:
- CODECOV_TOKEN="1020bcfd-ec5c-4880-a198-3c489f8554a0"
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

after_success:
  - npm run coverage
  - codecov
  - cat ./coverage/lcov.info | coveralls
  - bash <(curl -s https://codecov.io/bash)
